name: Docker Image CI

on:
  push:
    branches:
      - master
    paths-ignore:
      - README.md
jobs:

  build:

    runs-on: [ubuntu-latest]

    steps:
    - name: checkout code
      uses: actions/checkout@v2

    - name: Build and push Docker images to dockerhub
      uses: docker/build-push-action@v1
      with:
        username: iyjian
        password: ${{ secrets.DOCKERHUB_PASSWORD }}
        repository: iyjian/docker-ssh-tunnel
        tag_with_ref: true
